/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  BaseController,
  BaseControllerInterface,
} from "../BaseController";

const _abi = [
  {
    inputs: [],
    name: "ownerAddr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managerAddr",
        type: "address",
      },
    ],
    name: "setManager",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610188806100326000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80639c675eaa14610046578063d0ebdbe714610075578063f2fde38b1461008a575b600080fd5b600054610059906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b610088610083366004610122565b61009d565b005b610088610098366004610122565b6100d6565b6000546001600160a01b031633146100b457600080fd5b600180546001600160a01b0319166001600160a01b0392909216919091179055565b6000546001600160a01b031633146100ed57600080fd5b6001600160a01b03811661010057600080fd5b600080546001600160a01b0319166001600160a01b0392909216919091179055565b60006020828403121561013457600080fd5b81356001600160a01b038116811461014b57600080fd5b939250505056fea2646970667358221220bb7610ed2f69d999411b9c575e5cbfc02c9a23159bfaeaff25e14a4dad1327f364736f6c63430008090033";

type BaseControllerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BaseControllerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class BaseController__factory extends ContractFactory {
  constructor(...args: BaseControllerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<BaseController> {
    return super.deploy(overrides || {}) as Promise<BaseController>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): BaseController {
    return super.attach(address) as BaseController;
  }
  connect(signer: Signer): BaseController__factory {
    return super.connect(signer) as BaseController__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BaseControllerInterface {
    return new utils.Interface(_abi) as BaseControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BaseController {
    return new Contract(address, _abi, signerOrProvider) as BaseController;
  }
}
