/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  UserController,
  UserControllerInterface,
} from "../UserController";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_username",
        type: "bytes32",
      },
    ],
    name: "createUser",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "ownerAddr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_managerAddr",
        type: "address",
      },
    ],
    name: "setManagerAddr",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50600080546001600160a01b03191633179055610334806100326000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80637978b231146100515780639c675eaa14610066578063abf7bfd814610096578063f2fde38b146100b7575b600080fd5b61006461005f36600461028b565b6100ca565b005b600054610079906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6100a96100a43660046102af565b610103565b60405190815260200161008d565b6100646100c536600461028b565b610227565b6000546001600160a01b031633146100e157600080fd5b600180546001600160a01b0319166001600160a01b0392909216919091179055565b60015460405163bf40fac160e01b815260206004820152600b60248201526a5573657253746f7261676560a81b60448201526000916001600160a01b0316908290829063bf40fac19060640160206040518083038186803b15801561016757600080fd5b505afa15801561017b573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061019f91906102c8565b60405163157ef7fb60e31b81526004810186905290915081906001600160a01b0382169063abf7bfd890602401602060405180830381600087803b1580156101e657600080fd5b505af11580156101fa573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061021e91906102e5565b95945050505050565b6000546001600160a01b0316331461023e57600080fd5b6001600160a01b03811661025157600080fd5b600080546001600160a01b0319166001600160a01b0392909216919091179055565b6001600160a01b038116811461028857600080fd5b50565b60006020828403121561029d57600080fd5b81356102a881610273565b9392505050565b6000602082840312156102c157600080fd5b5035919050565b6000602082840312156102da57600080fd5b81516102a881610273565b6000602082840312156102f757600080fd5b505191905056fea2646970667358221220c7230d615de37d5ff9cdc25da69790bdba3a9908f4031781e64d77b4169e3a2864736f6c63430008090033";

type UserControllerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserControllerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserController__factory extends ContractFactory {
  constructor(...args: UserControllerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<UserController> {
    return super.deploy(overrides || {}) as Promise<UserController>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): UserController {
    return super.attach(address) as UserController;
  }
  connect(signer: Signer): UserController__factory {
    return super.connect(signer) as UserController__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserControllerInterface {
    return new utils.Interface(_abi) as UserControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UserController {
    return new Contract(address, _abi, signerOrProvider) as UserController;
  }
}
