/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface UserStorageInterface extends utils.Interface {
  functions: {
    "createUser(bytes32)": FunctionFragment;
    "getUserFromId(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createUser",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserFromId",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserFromId",
    data: BytesLike
  ): Result;

  events: {};
}

export interface UserStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: UserStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createUser(
      _username: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getUserFromId(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;
  };

  createUser(
    _username: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getUserFromId(
    _userId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string]>;

  callStatic: {
    createUser(
      _username: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUserFromId(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string]>;
  };

  filters: {};

  estimateGas: {
    createUser(
      _username: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getUserFromId(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createUser(
      _username: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getUserFromId(
      _userId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
